snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/24/7.yaml # GHC 9.10.2

packages:
  - .

build:
  haddock: true
  haddock-deps: false
  haddock-arguments:
    haddock-args:
      - "--odir=haddock"
